/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  PinIn,
  PinOut,
  PinUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getListPinsV1PinsGetUrl = () => {




  return `/v1/pins`
}

/**
 * Get a list of Pins
 * @summary List Pins
 */
export const listPinsV1PinsGet = async ( options?: RequestInit): Promise<PinOut[]> => {

  return minecraftFetch<PinOut[]>(getListPinsV1PinsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreatePinV1PinsPostUrl = () => {




  return `/v1/pins`
}

/**
 * Creates a new pin
 * @summary Create Pin
 */
export const createPinV1PinsPost = async (pinIn: PinIn, options?: RequestInit): Promise<PinOut> => {

  return minecraftFetch<PinOut>(getCreatePinV1PinsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinIn)
  }
);}


export const getGetPinV1PinsPinIdGetUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Returns the pin specified
 * @summary Get Pin
 */
export const getPinV1PinsPinIdGet = async (pinId: number, options?: RequestInit): Promise<PinOut> => {

  return minecraftFetch<PinOut>(getGetPinV1PinsPinIdGetUrl(pinId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdatePinV1PinsPinIdPutUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Update Pin
 *
 * Update the pin. Anything that you do not want to update can be left as `null`
 * @summary Partial Update Pin
 */
export const partialUpdatePinV1PinsPinIdPut = async (pinId: number,
    pinUpdate: PinUpdate, options?: RequestInit): Promise<PinOut> => {

  return minecraftFetch<PinOut>(getPartialUpdatePinV1PinsPinIdPutUrl(pinId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinUpdate)
  }
);}


export const getPartialUpdatePinV1PinsPinIdPatchUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Update Pin
 *
 * Update the pin. Anything that you do not want to update can be left as `null`
 * @summary Partial Update Pin
 */
export const partialUpdatePinV1PinsPinIdPatch = async (pinId: number,
    pinUpdate: PinUpdate, options?: RequestInit): Promise<PinOut> => {

  return minecraftFetch<PinOut>(getPartialUpdatePinV1PinsPinIdPatchUrl(pinId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinUpdate)
  }
);}


