/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  EventIn,
  EventOut,
  EventUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getListEventsV1GuildsMeEventsGetUrl = () => {




  return `/v1/guilds/me/events`
}

/**
 * Get a list of Events
 * @summary List Events
 */
export const listEventsV1GuildsMeEventsGet = async ( options?: RequestInit): Promise<EventOut[]> => {

  return minecraftFetch<EventOut[]>(getListEventsV1GuildsMeEventsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateEventV1GuildsMeEventsPostUrl = () => {




  return `/v1/guilds/me/events`
}

/**
 * Creates a new event
 * @summary Create Event
 */
export const createEventV1GuildsMeEventsPost = async (eventIn: EventIn, options?: RequestInit): Promise<EventOut> => {

  return minecraftFetch<EventOut>(getCreateEventV1GuildsMeEventsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(eventIn)
  }
);}


export const getGetEventV1GuildsMeEventsEventIdGetUrl = (eventId: number,) => {




  return `/v1/guilds/me/events/${eventId}`
}

/**
 * Returns the event specified
 * @summary Get Event
 */
export const getEventV1GuildsMeEventsEventIdGet = async (eventId: number, options?: RequestInit): Promise<EventOut> => {

  return minecraftFetch<EventOut>(getGetEventV1GuildsMeEventsEventIdGetUrl(eventId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateEventV1GuildsMeEventsEventIdPutUrl = (eventId: number,) => {




  return `/v1/guilds/me/events/${eventId}`
}

/**
 * Update Event
 * @summary Partial Update Event
 */
export const partialUpdateEventV1GuildsMeEventsEventIdPut = async (eventId: number,
    eventUpdate: EventUpdate, options?: RequestInit): Promise<EventOut> => {

  return minecraftFetch<EventOut>(getPartialUpdateEventV1GuildsMeEventsEventIdPutUrl(eventId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(eventUpdate)
  }
);}


export const getPartialUpdateEventV1GuildsMeEventsEventIdPatchUrl = (eventId: number,) => {




  return `/v1/guilds/me/events/${eventId}`
}

/**
 * Update Event
 * @summary Partial Update Event
 */
export const partialUpdateEventV1GuildsMeEventsEventIdPatch = async (eventId: number,
    eventUpdate: EventUpdate, options?: RequestInit): Promise<EventOut> => {

  return minecraftFetch<EventOut>(getPartialUpdateEventV1GuildsMeEventsEventIdPatchUrl(eventId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(eventUpdate)
  }
);}


