/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  InteractionSummary,
  LookupUserV1GuildsMeUsersLookupGetParams,
  PlaytimeSummary,
  ProfileOut,
  ProfileUpdate,
  UserIn,
  UserOut,
  UserUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getCreateUserV1GuildsMeUsersPostUrl = () => {




  return `/v1/guilds/me/users`
}

/**
 * Creates a new user in the guild.
 * @summary Create User
 */
export const createUserV1GuildsMeUsersPost = async (userIn: UserIn, options?: RequestInit): Promise<UserOut> => {

  return minecraftFetch<UserOut>(getCreateUserV1GuildsMeUsersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userIn)
  }
);}


export const getLookupUserV1GuildsMeUsersLookupGetUrl = (params?: LookupUserV1GuildsMeUsersLookupGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/users/lookup?${stringifiedParams}` : `/v1/guilds/me/users/lookup`
}

/**
 * Looks up a guild member by gamertag, whitelisted gamertag, or Discord ID.
 * Exactly one parameter must be provided.
 * @summary Lookup User
 */
export const lookupUserV1GuildsMeUsersLookupGet = async (params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: RequestInit): Promise<UserOut> => {

  return minecraftFetch<UserOut>(getLookupUserV1GuildsMeUsersLookupGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetUserV1GuildsMeUsersThornyIdGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This returns the User object
 * @summary Get User
 */
export const getUserV1GuildsMeUsersThornyIdGet = async (thornyId: number, options?: RequestInit): Promise<UserOut> => {

  return minecraftFetch<UserOut>(getGetUserV1GuildsMeUsersThornyIdGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateUserV1GuildsMeUsersThornyIdPatchUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This updates a user. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 *
 * `whitelist` does not apply to this. If you set it to null, it will become null.
 * @summary Partial Update User
 */
export const partialUpdateUserV1GuildsMeUsersThornyIdPatch = async (thornyId: number,
    userUpdate: UserUpdate, options?: RequestInit): Promise<UserOut> => {

  return minecraftFetch<UserOut>(getPartialUpdateUserV1GuildsMeUsersThornyIdPatchUrl(thornyId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdate)
  }
);}


export const getPartialUpdateUserV1GuildsMeUsersThornyIdPutUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This updates a user. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 *
 * `whitelist` does not apply to this. If you set it to null, it will become null.
 * @summary Partial Update User
 */
export const partialUpdateUserV1GuildsMeUsersThornyIdPut = async (thornyId: number,
    userUpdate: UserUpdate, options?: RequestInit): Promise<UserOut> => {

  return minecraftFetch<UserOut>(getPartialUpdateUserV1GuildsMeUsersThornyIdPutUrl(thornyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdate)
  }
);}


export const getGetUserProfileV1GuildsMeUsersThornyIdProfileGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This returns the user's profile.
 *
 * Will be removed in a future release. Use `/users/{thorny_id}` instead.
 * @deprecated
 * @summary Get User Profile
 */
export const getUserProfileV1GuildsMeUsersThornyIdProfileGet = async (thornyId: number, options?: RequestInit): Promise<ProfileOut> => {

  return minecraftFetch<ProfileOut>(getGetUserProfileV1GuildsMeUsersThornyIdProfileGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This updates a user's profile. Anything set to NULL will be ignored.
 * @summary Partial Update Profile
 */
export const partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch = async (thornyId: number,
    profileUpdate: ProfileUpdate, options?: RequestInit): Promise<ProfileOut> => {

  return minecraftFetch<ProfileOut>(getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchUrl(thornyId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(profileUpdate)
  }
);}


export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This updates a user's profile. Anything set to NULL will be ignored.
 * @summary Partial Update Profile
 */
export const partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut = async (thornyId: number,
    profileUpdate: ProfileUpdate, options?: RequestInit): Promise<ProfileOut> => {

  return minecraftFetch<ProfileOut>(getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutUrl(thornyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(profileUpdate)
  }
);}


export const getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/playtime`
}

/**
 * This returns the user's playtime. Note that all playtime is in seconds!
 * @summary Get User Playtime
 */
export const getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet = async (thornyId: number, options?: RequestInit): Promise<PlaytimeSummary> => {

  return minecraftFetch<PlaytimeSummary>(getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/interactions`
}

/**
 * This returns the user's interaction summary.
 * This may take long to process, so ensure you have the proper timeouts set.
 * @summary Get User Interactions
 */
export const getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet = async (thornyId: number, options?: RequestInit): Promise<InteractionSummary> => {

  return minecraftFetch<InteractionSummary>(getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


