/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  BodyGetTokenAuthTokenPost,
  ClientCreateRequest,
  ClientCreateResponse,
  TokenResponse
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getGetTokenAuthTokenPostUrl = () => {




  return `/auth/token`
}

/**
 * @summary Get Token
 */
export const getTokenAuthTokenPost = async (bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: RequestInit): Promise<TokenResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyGetTokenAuthTokenPost?.grant_type !== undefined) {
 formUrlEncoded.append(`grant_type`, bodyGetTokenAuthTokenPost.grant_type);
 }
if(bodyGetTokenAuthTokenPost?.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyGetTokenAuthTokenPost.scope);
 }
if(bodyGetTokenAuthTokenPost?.guild_id !== undefined && bodyGetTokenAuthTokenPost.guild_id !== null) {
 formUrlEncoded.append(`guild_id`, bodyGetTokenAuthTokenPost.guild_id.toString())
 }
if(bodyGetTokenAuthTokenPost?.client_id !== undefined && bodyGetTokenAuthTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyGetTokenAuthTokenPost.client_id);
 }
if(bodyGetTokenAuthTokenPost?.client_secret !== undefined && bodyGetTokenAuthTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyGetTokenAuthTokenPost.client_secret);
 }

  return minecraftFetch<TokenResponse>(getGetTokenAuthTokenPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
);}


export const getRegisterClientAuthClientsPostUrl = () => {




  return `/auth/clients`
}

/**
 * Master-tier clients only. Creates a guild-scoped API key.
 * @summary Register Client
 */
export const registerClientAuthClientsPost = async (clientCreateRequest: ClientCreateRequest, options?: RequestInit): Promise<ClientCreateResponse> => {

  return minecraftFetch<ClientCreateResponse>(getRegisterClientAuthClientsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientCreateRequest)
  }
);}


