/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChannelOut,
  ConnectionIn,
  ConnectionOut,
  FeatureOut,
  GuildIn,
  GuildOut,
  GuildPlaytimeAnalysis,
  GuildUpdate,
  InteractionIn,
  InteractionOut,
  ListInteractionsV1GuildsMeInteractionsGetParams,
  ListSessionsV1GuildsMeSessionsGetParams,
  OnlineMember,
  SessionOut
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getCreateGuildV1GuildsPostUrl = () => {




  return `/v1/guilds`
}

/**
 * Creates a new guild. If a guild with this ID already exists, it returns a 400.
 * @summary Create Guild
 */
export const createGuildV1GuildsPost = async (guildIn: GuildIn, options?: RequestInit): Promise<GuildOut> => {

  return minecraftFetch<GuildOut>(getCreateGuildV1GuildsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(guildIn)
  }
);}


export const getGetGuildV1GuildsMeGetUrl = () => {




  return `/v1/guilds/me`
}

/**
 * Fetch your guild information
 * @summary Get Guild
 */
export const getGuildV1GuildsMeGet = async ( options?: RequestInit): Promise<GuildOut> => {

  return minecraftFetch<GuildOut>(getGetGuildV1GuildsMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateGuildV1GuildsMePutUrl = () => {




  return `/v1/guilds/me`
}

/**
 * Partially updates guild information. Both `PATCH` and `PUT` work the same way.
 * @summary Partial Update Guild
 */
export const partialUpdateGuildV1GuildsMePut = async (guildUpdate: GuildUpdate, options?: RequestInit): Promise<GuildOut> => {

  return minecraftFetch<GuildOut>(getPartialUpdateGuildV1GuildsMePutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(guildUpdate)
  }
);}


export const getPartialUpdateGuildV1GuildsMePatchUrl = () => {




  return `/v1/guilds/me`
}

/**
 * Partially updates guild information. Both `PATCH` and `PUT` work the same way.
 * @summary Partial Update Guild
 */
export const partialUpdateGuildV1GuildsMePatch = async (guildUpdate: GuildUpdate, options?: RequestInit): Promise<GuildOut> => {

  return minecraftFetch<GuildOut>(getPartialUpdateGuildV1GuildsMePatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(guildUpdate)
  }
);}


export const getListFeaturesV1GuildsMeFeaturesGetUrl = () => {




  return `/v1/guilds/me/features`
}

/**
 * Returns a list of features enabled for the authenticated guild.
 * @deprecated
 * @summary List Features
 */
export const listFeaturesV1GuildsMeFeaturesGet = async ( options?: RequestInit): Promise<FeatureOut[]> => {

  return minecraftFetch<FeatureOut[]>(getListFeaturesV1GuildsMeFeaturesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getListChannelsV1GuildsMeChannelsGetUrl = () => {




  return `/v1/guilds/me/channels`
}

/**
 * This returns a list of the guild's channels
 * @deprecated
 * @summary List Channels
 */
export const listChannelsV1GuildsMeChannelsGet = async ( options?: RequestInit): Promise<ChannelOut[]> => {

  return minecraftFetch<ChannelOut[]>(getListChannelsV1GuildsMeChannelsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetGuildPlaytimeV1GuildsMePlaytimeGetUrl = () => {




  return `/v1/guilds/me/playtime`
}

/**
 * This returns the guild's playtime summary. Playtime is in seconds.
 *
 * > [!warning]
 * > The playtime analysis is currently a work in progress, and may not have all data.
 * > Data shape might change in the future.
 * @summary Get Guild Playtime
 */
export const getGuildPlaytimeV1GuildsMePlaytimeGet = async ( options?: RequestInit): Promise<GuildPlaytimeAnalysis> => {

  return minecraftFetch<GuildPlaytimeAnalysis>(getGetGuildPlaytimeV1GuildsMePlaytimeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetOnlineMembersV1GuildsMeOnlineGetUrl = () => {




  return `/v1/guilds/me/online`
}

/**
 * Use /me/sessions instead for more accurate sessions data
 * @deprecated
 * @summary Get Online Members
 */
export const getOnlineMembersV1GuildsMeOnlineGet = async ( options?: RequestInit): Promise<OnlineMember[]> => {

  return minecraftFetch<OnlineMember[]>(getGetOnlineMembersV1GuildsMeOnlineGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getListSessionsV1GuildsMeSessionsGetUrl = (params?: ListSessionsV1GuildsMeSessionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/sessions?${stringifiedParams}` : `/v1/guilds/me/sessions`
}

/**
 * Returns a list of all sessions for the guild.
 * @summary List Sessions
 */
export const listSessionsV1GuildsMeSessionsGet = async (params?: ListSessionsV1GuildsMeSessionsGetParams, options?: RequestInit): Promise<SessionOut[]> => {

  return minecraftFetch<SessionOut[]>(getListSessionsV1GuildsMeSessionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateConnectionV1GuildsMeConnectionPostUrl = () => {




  return `/v1/guilds/me/connection`
}

/**
 * Creates a connection event.
 * @summary Create Connection
 */
export const createConnectionV1GuildsMeConnectionPost = async (connectionIn: ConnectionIn, options?: RequestInit): Promise<ConnectionOut> => {

  return minecraftFetch<ConnectionOut>(getCreateConnectionV1GuildsMeConnectionPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(connectionIn)
  }
);}


export const getCreateInteractionV1GuildsMeInteractionPostUrl = () => {




  return `/v1/guilds/me/interaction`
}

/**
 * Creates an interaction event.
 * @summary Create Interaction
 */
export const createInteractionV1GuildsMeInteractionPost = async (interactionIn: InteractionIn, options?: RequestInit): Promise<InteractionOut> => {

  return minecraftFetch<InteractionOut>(getCreateInteractionV1GuildsMeInteractionPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(interactionIn)
  }
);}


export const getListInteractionsV1GuildsMeInteractionsGetUrl = (params?: ListInteractionsV1GuildsMeInteractionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/interactions?${stringifiedParams}` : `/v1/guilds/me/interactions`
}

/**
 * Filter interactions by various criteria.
 * @summary List Interactions
 */
export const listInteractionsV1GuildsMeInteractionsGet = async (params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: RequestInit): Promise<InteractionOut[]> => {

  return minecraftFetch<InteractionOut[]>(getListInteractionsV1GuildsMeInteractionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


