/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListQuestsV1GuildsMeQuestsRouterGetParams,
  QuestIn,
  QuestOut,
  QuestProgressIn,
  QuestProgressOut,
  QuestProgressUpdate,
  QuestUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getCreateQuestV1GuildsMeQuestsRouterPostUrl = () => {




  return `/v1/guilds/me/quests_router`
}

/**
 * Create New Quest
 *
 * Creates a new quest based on the information provided.
 * Some fields are optional and can be `null` while others are required.
 * Check the schema for more info on that.
 * @summary Create Quest
 */
export const createQuestV1GuildsMeQuestsRouterPost = async (questIn: QuestIn, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getCreateQuestV1GuildsMeQuestsRouterPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questIn)
  }
);}


export const getListQuestsV1GuildsMeQuestsRouterGetUrl = (params?: ListQuestsV1GuildsMeQuestsRouterGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/quests_router?${stringifiedParams}` : `/v1/guilds/me/quests_router`
}

/**
 * Get a list of Quests
 * @summary List Quests
 */
export const listQuestsV1GuildsMeQuestsRouterGet = async (params?: ListQuestsV1GuildsMeQuestsRouterGetParams, options?: RequestInit): Promise<QuestOut[]> => {

  return minecraftFetch<QuestOut[]>(getListQuestsV1GuildsMeQuestsRouterGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetQuestV1GuildsMeQuestsRouterQuestIdGetUrl = (questId: number,) => {




  return `/v1/guilds/me/quests_router/${questId}`
}

/**
 * Get Quest
 *
 * Returns a specific quest, objectives and rewards
 * @summary Get Quest
 */
export const getQuestV1GuildsMeQuestsRouterQuestIdGet = async (questId: number, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getGetQuestV1GuildsMeQuestsRouterQuestIdGetUrl(questId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateQuestV1GuildsMeQuestsRouterQuestIdPutUrl = (questId: number,) => {




  return `/v1/guilds/me/quests_router/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsRouterQuestIdPut = async (questId: number,
    questUpdate: QuestUpdate, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsRouterQuestIdPutUrl(questId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questUpdate)
  }
);}


export const getPartialUpdateQuestV1GuildsMeQuestsRouterQuestIdPatchUrl = (questId: number,) => {




  return `/v1/guilds/me/quests_router/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsRouterQuestIdPatch = async (questId: number,
    questUpdate: QuestUpdate, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsRouterQuestIdPatchUrl(questId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questUpdate)
  }
);}


export const getCreateQuestProgressV1GuildsMeQuestsRouterProgressPostUrl = () => {




  return `/v1/guilds/me/quests_router/progress`
}

/**
 * Create New Quest Progress
 *
 * Adds a new quest to a user, tracking their progress.
 * Automatically sets the quest progress to "active".
 * @summary Create Quest Progress
 */
export const createQuestProgressV1GuildsMeQuestsRouterProgressPost = async (questProgressIn: QuestProgressIn, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getCreateQuestProgressV1GuildsMeQuestsRouterProgressPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressIn)
  }
);}


export const getListQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests_router/progress/user/${thornyId}`
}

/**
 * Get All User's Quest Progress
 *
 * Returns all quest progress belonging to a user
 * @summary List Quest Progress
 */
export const listQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdGet = async (thornyId: number, options?: RequestInit): Promise<QuestProgressOut[]> => {

  return minecraftFetch<QuestProgressOut[]>(getListQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests_router/progress/user/${thornyId}/active`
}

/**
 * Get User's Active Quest
 *
 * Returns the user's currently active quest.
 * @summary Get Active Quest Progress
 */
export const getActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveGet = async (thornyId: number, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getGetActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getFailActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveDeleteUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests_router/progress/user/${thornyId}/active`
}

/**
 * Fail User's Active Quest
 *
 * This marks the active quest and all of its objectives as "failed".
 * @summary Fail Active Quest Progress
 */
export const failActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveDelete = async (thornyId: number, options?: RequestInit): Promise<void> => {

  return minecraftFetch<void>(getFailActiveQuestProgressV1GuildsMeQuestsRouterProgressUserThornyIdActiveDeleteUrl(thornyId),
  {
    ...options,
    method: 'DELETE'


  }
);}


export const getPartialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPatchUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests_router/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPatch = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPatchUrl(progressId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressUpdate)
  }
);}


export const getPartialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPutUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests_router/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPut = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsRouterProgressProgressIdPutUrl(progressId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressUpdate)
  }
);}


