/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListQuestsV1GuildsMeQuestsGetParams,
  QuestIn,
  QuestOut,
  QuestProgressIn,
  QuestProgressOut,
  QuestProgressUpdate,
  QuestUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getCreateQuestV1GuildsMeQuestsPostUrl = () => {




  return `/v1/guilds/me/quests`
}

/**
 * Create New Quest
 *
 * Creates a new quest based on the information provided.
 * Some fields are optional and can be `null` while others are required.
 * Check the schema for more info on that.
 * @summary Create Quest
 */
export const createQuestV1GuildsMeQuestsPost = async (questIn: QuestIn, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getCreateQuestV1GuildsMeQuestsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questIn)
  }
);}


export const getListQuestsV1GuildsMeQuestsGetUrl = (params?: ListQuestsV1GuildsMeQuestsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/quests?${stringifiedParams}` : `/v1/guilds/me/quests`
}

/**
 * Get a list of Quests
 * @summary List Quests
 */
export const listQuestsV1GuildsMeQuestsGet = async (params?: ListQuestsV1GuildsMeQuestsGetParams, options?: RequestInit): Promise<QuestOut[]> => {

  return minecraftFetch<QuestOut[]>(getListQuestsV1GuildsMeQuestsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetQuestV1GuildsMeQuestsQuestIdGetUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Get Quest
 *
 * Returns a specific quest, objectives and rewards
 * @summary Get Quest
 */
export const getQuestV1GuildsMeQuestsQuestIdGet = async (questId: number, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getGetQuestV1GuildsMeQuestsQuestIdGetUrl(questId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsQuestIdPut = async (questId: number,
    questUpdate: QuestUpdate, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutUrl(questId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questUpdate)
  }
);}


export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsQuestIdPatch = async (questId: number,
    questUpdate: QuestUpdate, options?: RequestInit): Promise<QuestOut> => {

  return minecraftFetch<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchUrl(questId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questUpdate)
  }
);}


export const getCreateQuestProgressV1GuildsMeQuestsProgressPostUrl = () => {




  return `/v1/guilds/me/quests/progress`
}

/**
 * Create New Quest Progress
 *
 * Adds a new quest to a user, tracking their progress.
 * Automatically sets the quest progress to "active".
 * @summary Create Quest Progress
 */
export const createQuestProgressV1GuildsMeQuestsProgressPost = async (questProgressIn: QuestProgressIn, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getCreateQuestProgressV1GuildsMeQuestsProgressPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressIn)
  }
);}


export const getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}`
}

/**
 * Get All User's Quest Progress
 *
 * Returns all quest progress belonging to a user
 * @summary List Quest Progress
 */
export const listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet = async (thornyId: number, options?: RequestInit): Promise<QuestProgressOut[]> => {

  return minecraftFetch<QuestProgressOut[]>(getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}/active`
}

/**
 * Get User's Active Quest
 *
 * Returns the user's currently active quest.
 * @summary Get Active Quest Progress
 */
export const getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet = async (thornyId: number, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}/active`
}

/**
 * Fail User's Active Quest
 *
 * This marks the active quest and all of its objectives as "failed".
 * @summary Fail Active Quest Progress
 */
export const failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete = async (thornyId: number, options?: RequestInit): Promise<void> => {

  return minecraftFetch<void>(getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteUrl(thornyId),
  {
    ...options,
    method: 'DELETE'


  }
);}


export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchUrl(progressId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressUpdate)
  }
);}


export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: RequestInit): Promise<QuestProgressOut> => {

  return minecraftFetch<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutUrl(progressId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questProgressUpdate)
  }
);}


