/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListWikiPagesV1GuildsMeWikiGetParams,
  PageIn,
  PageOut,
  PageUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getListWikiPagesV1GuildsMeWikiGetUrl = (params?: ListWikiPagesV1GuildsMeWikiGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const arrayFormatParameters = ["tags"];

    if (Array.isArray(value) && arrayFormatParameters.includes(key)) {
      value.forEach((v) => { normalizedParams.append(key, v === null ? 'null' : String(v)); });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/wiki?${stringifiedParams}` : `/v1/guilds/me/wiki`
}

/**
 * Get a list of Wiki Pages
 * @summary List Wiki Pages
 */
export const listWikiPagesV1GuildsMeWikiGet = async (params?: ListWikiPagesV1GuildsMeWikiGetParams, options?: RequestInit): Promise<PageOut[]> => {

  return minecraftFetch<PageOut[]>(getListWikiPagesV1GuildsMeWikiGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateWikiPageV1GuildsMeWikiPostUrl = () => {




  return `/v1/guilds/me/wiki`
}

/**
 * Creates a new wiki page
 * @summary Create Wiki Page
 */
export const createWikiPageV1GuildsMeWikiPost = async (pageIn: PageIn, options?: RequestInit): Promise<PageOut> => {

  return minecraftFetch<PageOut>(getCreateWikiPageV1GuildsMeWikiPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pageIn)
  }
);}


export const getGetWikiPageV1GuildsMeWikiSlugGetUrl = (slug: string,) => {




  return `/v1/guilds/me/wiki/${slug}`
}

/**
 * Returns a wiki page
 * @summary Get Wiki Page
 */
export const getWikiPageV1GuildsMeWikiSlugGet = async (slug: string, options?: RequestInit): Promise<PageOut> => {

  return minecraftFetch<PageOut>(getGetWikiPageV1GuildsMeWikiSlugGetUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateWikiPageV1GuildsMeWikiSlugPutUrl = (slug: string,) => {




  return `/v1/guilds/me/wiki/${slug}`
}

/**
 * Returns a wiki page
 * @summary Partial Update Wiki Page
 */
export const partialUpdateWikiPageV1GuildsMeWikiSlugPut = async (slug: string,
    pageUpdate: PageUpdate, options?: RequestInit): Promise<PageOut> => {

  return minecraftFetch<PageOut>(getPartialUpdateWikiPageV1GuildsMeWikiSlugPutUrl(slug),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pageUpdate)
  }
);}


export const getPartialUpdateWikiPageV1GuildsMeWikiSlugPatchUrl = (slug: string,) => {




  return `/v1/guilds/me/wiki/${slug}`
}

/**
 * Returns a wiki page
 * @summary Partial Update Wiki Page
 */
export const partialUpdateWikiPageV1GuildsMeWikiSlugPatch = async (slug: string,
    pageUpdate: PageUpdate, options?: RequestInit): Promise<PageOut> => {

  return minecraftFetch<PageOut>(getPartialUpdateWikiPageV1GuildsMeWikiSlugPatchUrl(slug),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pageUpdate)
  }
);}


