/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  PresignIn,
  PresignOut
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getGetPresignedUploadUrlV1ImagesPresignPostUrl = () => {




  return `/v1/images/presign`
}

/**
 * @summary Get Presigned Upload Url
 */
export const getPresignedUploadUrlV1ImagesPresignPost = async (presignIn: PresignIn, options?: RequestInit): Promise<PresignOut> => {

  return minecraftFetch<PresignOut>(getGetPresignedUploadUrlV1ImagesPresignPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(presignIn)
  }
);}


