/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CtaButtonVariant } from './ctaButtonVariant';

export interface CtaButton {
  /** The button label */
  label: string;
  /** The button destination URL */
  url: string;
  /** Phosphor icon component name */
  icon?: string | null;
  /** The button's visual weight */
  variant?: CtaButtonVariant;
}
