/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface DeliverTargetProgressModel {
  /** The target uuid */
  target_uuid?: string;
  target_type: 'deliver';
  /** The number of items/entities logged so far */
  count?: number;
}
