/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface DeliverTargetModel {
  /** The target uuid */
  target_uuid?: string;
  /** The type of the target. Must be equal to `objective_type`. */
  target_type: 'deliver';
  /** The number of this target to be reached. At least 1. */
  count: number;
  /**
     * The coordinates
     * @minItems 3
     * @maxItems 3
     */
  coordinates: [number, number, number];
  /** The horizontal radius to check for (x and z axis) */
  horizontal_radius: number;
  /** The vertical radius to check for (y axis) */
  vertical_radius?: number | null;
  /** The item to be delivered. If this is present, `entity` should not be. */
  item?: string | null;
  /** The entity to be delivered. If this is present, `item` should not be. */
  entity?: string | null;
}
