/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of interaction
 */
export type ListInteractionsV1GuildsMeInteractionsGetInteractionTypesItem = typeof ListInteractionsV1GuildsMeInteractionsGetInteractionTypesItem[keyof typeof ListInteractionsV1GuildsMeInteractionsGetInteractionTypesItem];


export const ListInteractionsV1GuildsMeInteractionsGetInteractionTypesItem = {
  kill: 'kill',
  mine: 'mine',
  place: 'place',
  use: 'use',
  die: 'die',
  scriptevent: 'scriptevent',
} as const;
