/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type ObjectiveUpdateObjectiveType = typeof ObjectiveUpdateObjectiveType[keyof typeof ObjectiveUpdateObjectiveType] | null;


export const ObjectiveUpdateObjectiveType = {
  kill: 'kill',
  mine: 'mine',
  scriptevent: 'scriptevent',
  visit: 'visit',
} as const;
