/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomizationsInput } from './customizationsInput';
import type { KillTargetModel } from './killTargetModel';
import type { MineTargetModel } from './mineTargetModel';
import type { ObjectiveUpdateLogic } from './objectiveUpdateLogic';
import type { ObjectiveUpdateObjectiveType } from './objectiveUpdateObjectiveType';
import type { RewardUpdate } from './rewardUpdate';
import type { ScriptEventTargetModel } from './scriptEventTargetModel';
import type { VisitTargetModel } from './visitTargetModel';

export interface ObjectiveUpdate {
  objective_id?: number | null;
  description?: string | null;
  display?: string | null;
  order_index?: number | null;
  objective_type?: ObjectiveUpdateObjectiveType;
  logic?: ObjectiveUpdateLogic;
  target_count?: number | null;
  targets?: (MineTargetModel | KillTargetModel | ScriptEventTargetModel | VisitTargetModel)[] | null;
  customizations?: CustomizationsInput | null;
  rewards?: RewardUpdate[] | null;
}
