/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of objective
 */
export type ObjectiveOutObjectiveType = typeof ObjectiveOutObjectiveType[keyof typeof ObjectiveOutObjectiveType];


export const ObjectiveOutObjectiveType = {
  kill: 'kill',
  mine: 'mine',
  scriptevent: 'scriptevent',
  visit: 'visit',
} as const;
