/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomizationProgress } from './customizationProgress';
import type { KillTargetProgressModel } from './killTargetProgressModel';
import type { MineTargetProgressModel } from './mineTargetProgressModel';
import type { ObjectiveProgressUpdateStatus } from './objectiveProgressUpdateStatus';
import type { ScriptEventTargetProgressModel } from './scriptEventTargetProgressModel';
import type { VisitTargetProgressModel } from './visitTargetProgressModel';

export interface ObjectiveProgressUpdate {
  objective_id?: number | null;
  start_time?: string | null;
  end_time?: string | null;
  status?: ObjectiveProgressUpdateStatus;
  target_progress?: (MineTargetProgressModel | KillTargetProgressModel | ScriptEventTargetProgressModel | VisitTargetProgressModel)[] | null;
  customization_progress?: CustomizationProgress | null;
}
