/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of waypoint to show
 */
export type WaypointCustomizationWaypointType = typeof WaypointCustomizationWaypointType[keyof typeof WaypointCustomizationWaypointType];


export const WaypointCustomizationWaypointType = {
  boss: 'boss',
  house: 'house',
  question: 'question',
} as const;
