/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { WaypointCustomizationWaypointType } from './waypointCustomizationWaypointType';

export interface WaypointCustomization {
  /**
     * The coordinates to show the waypoint at
     * @minItems 3
     * @maxItems 3
     */
  coordinates: [number, number, number];
  /** The type of waypoint to show */
  waypoint_type: WaypointCustomizationWaypointType;
}
