/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  LeaderboardModel
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetUrl = (month: string,) => {




  return `/v1/guilds/me/leaderboard/playtime/${month}`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Playtime Leaderboard
 */
export const getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet = async (month: string, options?: RequestInit): Promise<LeaderboardModel> => {

  return minecraftFetch<LeaderboardModel>(getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetUrl(month),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetUrl = () => {




  return `/v1/guilds/me/leaderboard/currency`
}

/**
 * Returns the guild's currency leaderboard, in order.
 * @summary Get Currency Leaderboard
 */
export const getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return minecraftFetch<LeaderboardModel>(getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetUrl = () => {




  return `/v1/guilds/me/leaderboard/levels`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Levels Leaderboard
 */
export const getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return minecraftFetch<LeaderboardModel>(getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsRouterGetUrl = () => {




  return `/v1/guilds/me/leaderboard/quests_router`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Quests Leaderboard
 */
export const getQuestsLeaderboardV1GuildsMeLeaderboardQuestsRouterGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return minecraftFetch<LeaderboardModel>(getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsRouterGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


