/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  RelayModel
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getServerRelayV1RelayPostUrl = () => {




  return `/v1/relay`
}

/**
 * Relays a message to the discord server via a webhook.
 * Essentially acts as a wrapper, instead of calling a HTTP to the
 * webhook, just send a POST to here.
 * @summary Server Relay
 */
export const serverRelayV1RelayPost = async (relayModel: RelayModel, options?: RequestInit): Promise<RelayModel> => {

  return minecraftFetch<RelayModel>(getServerRelayV1RelayPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(relayModel)
  }
);}


