/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ItemCreateModel,
  ItemListModel,
  ItemModel,
  ItemUpdateModel,
  WorldOut,
  WorldUpdate
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getGetWorldV1GuildsMeWorldsGetUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Get World
 */
export const getWorldV1GuildsMeWorldsGet = async ( options?: RequestInit): Promise<WorldOut> => {

  return minecraftFetch<WorldOut>(getGetWorldV1GuildsMeWorldsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateWorldV1GuildsMeWorldsPutUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Partial Update World
 */
export const partialUpdateWorldV1GuildsMeWorldsPut = async (worldUpdate: WorldUpdate, options?: RequestInit): Promise<WorldOut> => {

  return minecraftFetch<WorldOut>(getPartialUpdateWorldV1GuildsMeWorldsPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(worldUpdate)
  }
);}


export const getPartialUpdateWorldV1GuildsMeWorldsPatchUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Partial Update World
 */
export const partialUpdateWorldV1GuildsMeWorldsPatch = async (worldUpdate: WorldUpdate, options?: RequestInit): Promise<WorldOut> => {

  return minecraftFetch<WorldOut>(getPartialUpdateWorldV1GuildsMeWorldsPatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(worldUpdate)
  }
);}


export const getListItemsV1GuildsMeWorldsItemsGetUrl = () => {




  return `/v1/guilds/me/worlds/items`
}

/**
 * Get All Item
 *
 * This returns a list of all Items
 * @summary List Items
 */
export const listItemsV1GuildsMeWorldsItemsGet = async ( options?: RequestInit): Promise<ItemListModel> => {

  return minecraftFetch<ItemListModel>(getListItemsV1GuildsMeWorldsItemsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateItemV1GuildsMeWorldsItemsPostUrl = () => {




  return `/v1/guilds/me/worlds/items`
}

/**
 * Create New Item
 *
 * Creates a new item to be available for sacrificing
 * If an item with these ID's already exists, it returns a 500.
 * @summary Create Item
 */
export const createItemV1GuildsMeWorldsItemsPost = async (itemCreateModel: ItemCreateModel, options?: RequestInit): Promise<ItemModel> => {

  return minecraftFetch<ItemModel>(getCreateItemV1GuildsMeWorldsItemsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(itemCreateModel)
  }
);}


export const getGetItemV1GuildsMeWorldsItemsItemIdGetUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Get Item
 *
 * This returns the Item
 * @summary Get Item
 */
export const getItemV1GuildsMeWorldsItemsItemIdGet = async (itemId: string, options?: RequestInit): Promise<ItemModel> => {

  return minecraftFetch<ItemModel>(getGetItemV1GuildsMeWorldsItemsItemIdGetUrl(itemId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Update Item
 *
 * This updates an item. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 * @summary Partial Update Item
 */
export const partialUpdateItemV1GuildsMeWorldsItemsItemIdPut = async (itemId: string,
    itemUpdateModel: ItemUpdateModel, options?: RequestInit): Promise<ItemModel> => {

  return minecraftFetch<ItemModel>(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutUrl(itemId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(itemUpdateModel)
  }
);}


export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Update Item
 *
 * This updates an item. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 * @summary Partial Update Item
 */
export const partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch = async (itemId: string,
    itemUpdateModel: ItemUpdateModel, options?: RequestInit): Promise<ItemModel> => {

  return minecraftFetch<ItemModel>(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchUrl(itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(itemUpdateModel)
  }
);}


