/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type {
  ProjectIn,
  ProjectOut,
  ProjectUpdate,
  StatusIn,
  StatusOut
} from '../model';

import { minecraftFetch } from '../../minecraft-fetch';

export const getListProjectsV1GuildsMeProjectsGetUrl = () => {




  return `/v1/guilds/me/projects`
}

/**
 * Get a list of Projects
 * @summary List Projects
 */
export const listProjectsV1GuildsMeProjectsGet = async ( options?: RequestInit): Promise<ProjectOut[]> => {

  return minecraftFetch<ProjectOut[]>(getListProjectsV1GuildsMeProjectsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateProjectV1GuildsMeProjectsPostUrl = () => {




  return `/v1/guilds/me/projects`
}

/**
 * Creates a new project with a status, members and content.
 * @summary Create Project
 */
export const createProjectV1GuildsMeProjectsPost = async (projectIn: ProjectIn, options?: RequestInit): Promise<ProjectOut> => {

  return minecraftFetch<ProjectOut>(getCreateProjectV1GuildsMeProjectsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectIn)
  }
);}


export const getGetProjectV1GuildsMeProjectsProjectIdGetUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Returns the project specified
 * @summary Get Project
 */
export const getProjectV1GuildsMeProjectsProjectIdGet = async (projectId: string, options?: RequestInit): Promise<ProjectOut> => {

  return minecraftFetch<ProjectOut>(getGetProjectV1GuildsMeProjectsProjectIdGetUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Update the project.
 * @summary Partial Update Project
 */
export const partialUpdateProjectV1GuildsMeProjectsProjectIdPatch = async (projectId: string,
    projectUpdate: ProjectUpdate, options?: RequestInit): Promise<ProjectOut> => {

  return minecraftFetch<ProjectOut>(getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchUrl(projectId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectUpdate)
  }
);}


export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Update the project.
 * @summary Partial Update Project
 */
export const partialUpdateProjectV1GuildsMeProjectsProjectIdPut = async (projectId: string,
    projectUpdate: ProjectUpdate, options?: RequestInit): Promise<ProjectOut> => {

  return minecraftFetch<ProjectOut>(getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutUrl(projectId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectUpdate)
  }
);}


export const getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}/status`
}

/**
 * Returns the project's status
 * @deprecated
 * @summary Get Project Status
 */
export const getProjectStatusV1GuildsMeProjectsProjectIdStatusGet = async (projectId: string, options?: RequestInit): Promise<StatusOut> => {

  return minecraftFetch<StatusOut>(getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}


export const getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}/status`
}

/**
 * New Project Status
 *
 * Insert a new project status.
 * @summary Create Project Status
 */
export const createProjectStatusV1GuildsMeProjectsProjectIdStatusPost = async (projectId: string,
    statusIn: StatusIn, options?: RequestInit): Promise<StatusOut> => {

  return minecraftFetch<StatusOut>(getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(statusIn)
  }
);}


